### ISSUE TITLE
Foto(Photo)

### ISSUE THREAD

**Issue by DannyAdrian** [alvareztech/GoogleSignInAndroid#1]
Cuando el usuario no cuenta con una imagen en su correo provoca un error

**Comment by alvareztech** [comment]
Gracias por el Issue @DannyAdrian. Acabo de actualizar el proyecto y probe con una cuenta sin fotografía. No encontré el error, quizá por la actualización.

Si puedes probarlo ahora, puede que no sea necesaria la validación para la fotografía.
